# -*- coding: utf-8 -*-
"""Template Eksperimen MSML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxZ4Kc8XvisGuF1_VAneMiBYIP_grdjl
"""

import os
import argparse
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder

def clean_and_preprocess(input_path, output_path):
    print(f"🎬 Memulai proses preprocessing untuk: {input_path}")

    # 1. Load Dataset
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"File {input_path} tidak ditemukan!")
    df = pd.read_csv(input_path)

    # 2. Handling Duplicates
    df_cleaned = df.drop_duplicates().copy()
    print(f"   ↳ Data duplikat dihapus. Sisa baris: {len(df_cleaned)}")

    # 3. Encoding Target (placement_status) -> 1 jika Placed, 0 jika Not Placed
    # Menggunakan mapping manual agar konsisten daripada get_dummies boolean
    if 'placement_status' in df_cleaned.columns:
        df_cleaned['target'] = df_cleaned['placement_status'].apply(lambda x: 1 if x == 'Placed' else 0)
        df_cleaned = df_cleaned.drop(columns=['placement_status'])
    else:
        raise KeyError("Kolom 'placement_status' sebagai target tidak ditemukan!")

    # 4. Handling Outliers (IQR Capping)
    numerical_cols = ['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
                      'assignments_completed', 'previous_score', 'exam_score']

    print("   ↳ Melakukan IQR Capping pada fitur numerik...")
    for col in numerical_cols:
        Q1 = df_cleaned[col].quantile(0.25)
        Q3 = df_cleaned[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df_cleaned[col] = df_cleaned[col].clip(lower=lower_bound, upper=upper_bound)

    # 5. Binning & Label Encoding (study_hours & previous_score)
    print("   ↳ Membuat fitur binning...")
    # study_hours -> Low, Medium, High -> 0, 1, 2
    study_hours_bins = pd.cut(df_cleaned['study_hours'], bins=3, labels=['Low', 'Medium', 'High'], include_lowest=True)
    df_cleaned['study_hours_encoded'] = LabelEncoder().fit_transform(study_hours_bins)

    # previous_score -> Q1, Q2, Q3, Q4 -> 0, 1, 2, 3
    prev_score_bins = pd.qcut(df_cleaned['previous_score'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
    df_cleaned['previous_score_encoded'] = LabelEncoder().fit_transform(prev_score_bins)

    # 6. Fitur Standardisasi (StandardScaler)
    print("   ↳ Melakukan Standardisasi dengan StandardScaler...")
    scaler = StandardScaler()
    df_cleaned[numerical_cols] = scaler.fit_transform(df_cleaned[numerical_cols])

    # 7. Menyusun Urutan Kolom Final
    # Menempatkan target di paling ujung kanan demi kerapian data modeling
    feature_cols = [col for col in df_cleaned.columns if col != 'target']
    final_df = df_cleaned[feature_cols + ['target']]

    # 8. Save Data Sukses
    final_df.to_csv(output_path, index=False)
    print(f"✅ Preprocessing Selesai! Data disimpan di: {output_path}")
    print(f"📊 Dimensi Data Final: {final_df.shape}\n")

if __name__ == "__main__":
    # Setup argument parser agar script bisa dijalankan fleksibel via terminal/CLI
    parser = argparse.ArgumentParser(description="Automated Data Preprocessing Pipeline - MSML")
    parser.add_argument("--input", type=str, default="student_dataset_10000_rows.csv", help="Path ke file dataset mentah (CSV)")
    parser.add_argument("--output", type=str, default="student_dataset_clean.csv", help="Path hasil output dataset clean (CSV)")

    # Fix: Pass an empty list to parse_args() to ignore kernel-specific arguments
    args = parser.parse_args([])
    clean_and_preprocess(args.input, args.output)